services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    restart: unless-stopped

  updates_broker:
    build:
      context: ./broker_updates
    container_name: updates_broker
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/stocks_db
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./broker_updates:/app/broker_updates
    restart: unless-stopped

  requests_broker:
    build:
      context: ./broker_requests
    container_name: requests_broker
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/stocks_db
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./broker_requests:/app/broker_requests
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:

  mongo_data:

